runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  # Configure your database settings here
  DB_CONNECTION: mysql
  DB_HOST: your_mysql_host
  DB_DATABASE: lincBd
  DB_USERNAME: lincdb
  DB_PASSWORD: linc@2023

beta_settings:
  cloud_sql_instances: your_project_id:your_region:your_instance_name
